title: All-animation
description: All Animation.css é um conjunto de animações, divertidas para deixar seu projeto mais sexy. São animações cross-browser que darão mas ênfase a suas páginas como controles deslizantes, efeitos 3D’s..
google_analytics: UA-47249089-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
